### ISSUE TITLE
node index not running

### ISSUE THREAD

**Issue by iainvm** [JCB9090/pct-addon#1]
I don't seem to be getting any output or anything from "node index" 

My "npm install" did seem to end funny here's the output of it. However, running this command again doesn't give any output.

OS: Linux Mint 17.2

```
npm http GET https://registry.npmjs.org/is-symbol
npm http 304 https://registry.npmjs.org/is-symbol
npm http 304 https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/is-date-object
async@1.5.0 node_modules/async

needle@0.11.0 node_modules/needle
├── iconv-lite@0.4.13
└── debug@2.2.0 (ms@0.7.1)

lodash@3.10.1 node_modules/lodash

magnet-uri@5.1.1 node_modules/magnet-uri
├── uniq@1.0.1
├── xtend@4.0.1
└── thirty-two@1.0.1

stremio-addons@1.17.11 node_modules/stremio-addons
├── async@0.9.2
├── lodash@3.3.1
├── dot-object@1.3.1 (commander@2.9.0, glob@5.0.15)
└── tape@4.2.2 (inherits@2.0.1, has@1.0.1, defined@1.0.0, resumer@0.0.0, deep-equal@1.0.1, function-bind@1.0.2, through@2.3.8, object-inspect@1.0.2, glob@5.0.15, string.prototype.trim@1.1.1)
```

**Comment by JCB9090** [comment]
no input at all? does it quit immediately or does it stay running?

**Comment by iainvm** [comment]
Quits immediately, no output.

**Comment by iainvm** [comment]
it seems there is an issue with my "node" command, using the command "nodejs index" solved this and it ran as expected. must have the wrong package somewhere.

**Comment by JCB9090** [comment]
Good to know! Usually newer node's are with the cmd node but old ones were nodejs on linux
