### ISSUE TITLE
node index keeps running

### ISSUE THREAD

**Issue by josesanpedro** [JCB9090/pct-addon#2]
hi there, i installed on Windows like you said. but node index keeps running and never finish. its running now since 8 or 10 minutes displaying things like this:

> > stringifying cache took 31ms for 30000 items

seems like its listing content from popcortime.ws/api and storing locally.

its normal? i must run node index all the time or once every week to update local content?

thanks!

**Comment by Holsted777** [comment]
Must always run in the background

**Comment by josesanpedro** [comment]
thanks Holsted777. i will running as a service then...

**Comment by JCB9090** [comment]
yes, that's normal
