### ISSUE TITLE
country blocks yts.ag

### ISSUE THREAD

**Issue by ghost** [JCB9090/pct-addon#4]
My country (belgium) blocks [yts.ag](http://yts.ag) as shown in the screenshot below is there a way to bypass this?
this is the GitShell output:

C:\Users\alaa_\Documents\GitHub\pct-addon [master]> node index
-> map has 31018 movies / eps
-> eztv trying frm https://popcorntime.ws/api/eztv/shows/
Popcorn Addon listening on 7821
-> collecting from https://yts.ag/api/v2/list_movies.json
-> eztv trying frm https://popcornwvnbg7jev.onion.to/shows/
{ [Error: Hostname/IP doesn't match certificate's altnames: "Host: yts.ag. is not in the cert's altnames: DNS:_.services.belgium.be"]
  reason: 'Host: yts.ag. is not in the cert\'s altnames: DNS:_.services.belgium.be',
  host: 'yts.ag.',
  cert:
   { subject:
      { C: 'BE',
        ST: 'Brussels Hoofdstedelijk Gewest',
        L: 'Brussel',
        O: 'Federale Overheidsdienst Informatie- en Communicatietechnologie',
        OU: 'Fedict',
        CN: '_.services.belgium.be' },
     issuer:
      { C: 'BE',
        O: 'QuoVadis Trustlink BVBA',
        CN: 'QuoVadis Europe SSL CA G1' },
     subjectaltname: 'DNS:_.services.belgium.be',
     infoAccess: { 'CA Issuers - URI': [Object], 'OCSP - URI': [Object] },
     modulus: 'B0C853C3B899A1E7F9C22BD3E4246C908AD79CAA7E2C064E527347D5591753CE8850357133BFBA9732EEC25B9AFE2E4A6E5BEEE6066C87B25F4F3CCB76735D98FC077F10851F3F5FE4EF899E33734634B7CE149C2C6B6F30820C9BB0E9348CB7DA66A9FEB4EA1878C91E319965CDE1650561CF73A4E9BEA160D93B64DFA87C1956A2386A6AE3B3E4D49A10D9BEAD0BDA09E1BD9B3C134312337992F7211B9DE1B92547F4C0EA4726B668CBF9D0BD16BDF7EF95B86805F98C9B45A5B957E6E84E9605235C6A04F2260C2DBD8A0270C6B7401F14ABAF480215823A7E4281CE939CD47DD74F25A815D1C070796D531899999B540208F7743710F7A4BF7178EA75DB',
     exponent: '0x10001',
     valid_from: 'Aug  4 11:05:34 2015 GMT',
     valid_to: 'Aug  4 11:15:00 2018 GMT',
     fingerprint: '51:D8:2F:06:03:C1:5D:D3:10:32:87:3C:FC:EA:E5:39:50:89:84:26',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: '02AEE511CADD5BAF172943D616B67FED88069F3F',
     raw: <Buffer 30 82 06 50 30 82 04 38 a0 03 02 01 02 02 14 02 ae e5 11 ca dd 5b af 17 29 43 d6 16 b6 7f ed 88 06 9f 3f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 ... > } }
-> eztv responded from https://popcornwvnbg7jev.onion.to/shows/
-> collecting from https://popcornwvnbg7jev.onion.to/shows/
-> collecting from https://popcornwvnbg7jev.onion.to/shows/1
-> collecting from https://popcornwvnbg7jev.onion.to/shows/2
-> collecting from https://popcornwvnbg7jev.onion.to/shows/3
-> collecting from https://popcornwvnbg7jev.onion.to/shows/4
-> collecting from https://popcornwvnbg7jev.onion.to/shows/5
-> collecting from https://popcornwvnbg7jev.onion.to/shows/6
-> collecting from https://popcornwvnbg7jev.onion.to/shows/7
-> collecting from https://popcornwvnbg7jev.onion.to/shows/8
-> collecting from https://popcornwvnbg7jev.onion.to/shows/9
-> collecting from https://popcornwvnbg7jev.onion.to/shows/10
-> stringifying cache took 33ms for 31018 items

![capturie](https://cloud.githubusercontent.com/assets/9118794/12219845/72a1d208-b754-11e5-8df1-bfb47e3b3650.PNG)

**Comment by JCB9090** [comment]
it blocks my add-on (juan carlos torrents) too I think :) I don't know what we can do besides use vpn

**Comment by Holsted777** [comment]
Try changing DNS to open DNS and see if it works then.

**Comment by ghost** [comment]
juan carlos torrents works fine 
dns doesn't gonna try with a vpn
