### ISSUE TITLE
add-on is dead 

### ISSUE THREAD

**Issue by KillerCroc1** [JCB9090/pct-addon#5]
what is going on your add-on has vanished from the addons.strem.io page and is not active are you making changes to the add-on like eztv.ag and popcorntime.sh api ????

**Comment by KillerCroc1** [comment]
popcorntime.ws really man comon that is below the belt fix this asap to popcorntime.sh the official safe popcorntime

**Comment by KillerCroc1** [comment]
and eztvtorrent.com use eztv.ag get it together man we need this add-on as rarbg is launching its own add-on

**Comment by zroupas** [comment]
Hi, it's vanished and it's really a pitty. It was a great addon i hope someone can help with re enabling it

**Comment by KillerCroc1** [comment]
yeah i have been in contact with the .sh team and they seem interested :-) so hopefully that helps but all JCB has to do is change the source to popcorntime.sh lol

**Comment by zroupas** [comment]
Keep the pressure going :-)
I hope it pays off for all of us..

**Comment by KillerCroc1** [comment]
you can also help :-) if you want by sending a message on reddit tohttps://www.reddit.com/user/wallydz :-)

**Comment by zroupas** [comment]
I'm on it :-)

**Comment by AndyHoang** [comment]
i'm also waiting. Mean while you guys can try rarbg plugin: ```http://rarbg-addon.chapu.is/stremioget/stremio/v1```

**Comment by zroupas** [comment]
Great addon, thanks for pointing this out.I've installed it and works great. Let's hope pct-addon will come alive too..

**Comment by KillerCroc1** [comment]
Yeah had rarbg since it launched its awesome ;-) thanks anyway man
